### ISSUE TITLE
MyQ garage door stopped working

### ISSUE THREAD

**Issue by guoye-zhang** [koush/scrypted-myq#14]
Started happening this week, saw this message in the plugin events:

```
unhandledRejection TypeError: this.account.devices is not iterable
```

MyQ’s own app still works.

**Comment by otech** [comment]
Yes can second this, and noting that https://www.myliftmaster.com now says it's moved to mobile, I am guessing they have shut down the API by which this was working.

**Comment by nebhale** [comment]
@koush Just in case they figure out a work-around, Home Assistant is having the same problem: https://github.com/home-assistant/core/issues/99947

**Comment by otech** [comment]
There is some mention that it still works in Postman with a different user agent string, will have a go at testing this.

**Comment by koush** [comment]
fixed

**Comment by guoye-zhang** [comment]
This appears to have started again

https://github.com/home-assistant/core/issues/101763
